import React, { useCallback, useEffect, useMemo, useState } from 'react';
import MapPanel from './components/MapPanel'; import SearchBar from './components/SearchBar'; import Sidebar from './components/Sidebar'; import Timeline from './components/Timeline';
import AlertsPanel from './components/AlertsPanel';
import { alerts, cameras, demoPath } from './data/demoData'; import { getRoadRoute, searchPlate } from './services/anprApi';
export default function App() {
  const [selectedCamera,setSelectedCamera]=useState(cameras[0]), [tracedPlate,setTracedPlate]=useState(''), [path,setPath]=useState([]), [routeSegments,setRouteSegments]=useState([]), [loading,setLoading]=useState(false), [notice,setNotice]=useState('Showing congestion hotspots and camera status across the city.');
  const routeCameras=useMemo(()=>path.length?path:cameras,[path]);
  const decorate = route => route.map((point,index)=>({...point,delay:index===0?'usual':point.traffic==='high'?'late':point.traffic==='medium'?'watch':'usual'}));
  const trace = useCallback(async plate => { setLoading(true); try { const readings=await searchPlate(plate); const livePath=readings.map(r=>{const c=cameras.find(x=>x.id===r.camera_id||x.name===r.location); return c&&{...c,timestamp:r.timestamp,confidence:r.confidence||.8};}).filter(Boolean).reverse(); setPath(decorate(livePath.length>1?livePath:demoPath)); setTracedPlate(plate); setNotice(livePath.length>1?'Live ANPR sightings were used. The trajectory refreshes every 10 seconds.':'Demo route shown — map your camera IDs for live findings.'); } catch { setPath(decorate(demoPath)); setTracedPlate(plate); setNotice('Demo route shown — backend is offline or has no mapped readings.'); } finally { setLoading(false); } },[]);
  useEffect(()=>{ if(!tracedPlate) return; const timer=setInterval(()=>trace(tracedPlate),10000); return ()=>clearInterval(timer); },[tracedPlate,trace]);
  useEffect(()=>{ if(path.length<2){setRouteSegments([]);return;} let active=true; Promise.all(path.slice(1).map(async (point,index)=>({ ...point, points:await getRoadRoute(path[index].coords,point.coords).catch(()=>[path[index].coords,point.coords]) }))).then(routes=>active&&setRouteSegments(routes)); return ()=>{active=false;}; },[path]);
  function clearTrace(){setPath([]);setTracedPlate('');setNotice('Showing congestion hotspots and camera status across the city.');}
  return <main><header><div className="brand"><span>AN</span><div><h1>CityANPR Control Room</h1><p>ANPR + OCR · trajectory intelligence</p></div></div><SearchBar onSearch={trace} loading={loading}/></header><div className="notice">● {notice}{tracedPlate&&<button onClick={clearTrace}>Clear trace</button>}</div><div className="dashboard"><MapPanel cameras={routeCameras} path={path} routeSegments={routeSegments} selectedCamera={selectedCamera} onSelectCamera={setSelectedCamera}/><Sidebar camera={selectedCamera} cameras={cameras} tracedPlate={tracedPlate} path={path} onTrace={trace}/></div><div className="lower-grid"><AlertsPanel alerts={alerts} onTrace={trace}/>{tracedPlate&&<Timeline path={path} plate={tracedPlate}/>}</div></main>;
}
